crm/adv_company/urls.py
from django.urls import path

from .views import (
    AdvListView,
    AdvCreateView,
    AdvDetailView,
    AdvUpdateView,
    AdvDeleteView,
    AdvStatistics,
)

app_name = "advcompany"

urlpatterns = [
    path("ads/", AdvListView.as_view(), name="adv-list"),
    path("ads/<int:pk>/", AdvDetailView.as_view(), name="adv-edit"),
    path("ads/<int:pk>/edit/", AdvUpdateView.as_view()),
    path("ads/<int:pk>/delete/", AdvDeleteView.as_view()),
    path("ads/new/", AdvCreateView.as_view()),
    path("ads/statistic/", AdvStatistics.as_view()),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("service.urls")),
    path("", include("adv_company.urls")),
    path("", include("authentication.urls")),
    path("", include("users.urls")),
    path("", include("contracts.urls")),
    path("", include("customers.urls")),
]

crm/adv_company/models.py
from django.core.exceptions import ValidationError
from django.db import models

from service.models import Service


class AdvCompany(models.Model):
    """Модель рекламной кампании"""

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"

    name = models.CharField(
        unique=True, max_length=255, verbose_name="Название компании"
    )
    service = models.ManyToManyField(Service, verbose_name="Услуга")
    promotion_channel = models.CharField(
        max_length=127, verbose_name="Канал продвижения"
    )
    budget = models.DecimalField(
        default=0, max_digits=8, decimal_places=2, verbose_name="Бюджет"
    )

    def __str__(self):
        """Возвращает название рекламной кампании"""
        return self.name

    def clean(self):
        """Валидация данных"""
        if len(self.name) > 255:
            raise ValidationError('Длина названия не может превышать 255 символов')

        if len(self.promotion_channel) > 127:
            raise ValidationError('Длина канала продвижения не может превышать 127 символов')

        if self.budget < 0 or self.budget > 99999999.99:
            raise ValidationError('Бюджет должен быть в диапазоне 0.00 - 99,999,999.00')

    def save(self, *args, **kwargs):
        """Метод для сохранения данных при успешной валидации"""
        self.full_clean()
        return super().save(*args, **kwargs)

crm/contracts/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from service.models import Service


class Contract(models.Model):
    """Модель контракта"""

    class Meta:
        verbose_name = "Контракт"
        verbose_name_plural = "Контракты"

    name = models.CharField(
        unique=True, max_length=255, verbose_name="Название контракта"
    )
    service = models.ForeignKey(
        Service, on_delete=models.PROTECT, verbose_name="Услуга"
    )
    file = models.FileField(upload_to="contracts/documents/", verbose_name="Файл")
    start_date = models.DateField(default=timezone.now, verbose_name="Дата заключения")
    end_date = models.DateField(
        default=timezone.now() + timezone.timedelta(days=1),
        verbose_name="Дата расторжения",
    )

    @staticmethod
    def summa(pk):
        """Метод summa для вывода стоимости услуги, указанной в контракте"""
        product = Service.objects.get(id=pk)
        return product.price

    def __str__(self):
        """Возвращает название контракта"""
        return self.name

    def clean(self):
        """Валидация данных"""
        if len(self.name) > 255:
            print(self.name)
            raise ValidationError('Длина названия не может превышать 255 символов')

    def save(self, *args, **kwargs):
        """Метод для сохранения данных при успешной валидации"""
        self.full_clean()
        return super().save(*args, **kwargs)

crm/customers/models.py
from django.db import models

from users.models import Lead
from contracts.models import Contract


class Customer(models.Model):
    """Модель активного пользователя"""

    class Meta:
        verbose_name = "Активный пользователь"
        verbose_name_plural = "Активные пользователи"

    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, verbose_name='Пользователь')
    contract = models.ForeignKey(Contract, on_delete=models.SET_NULL, null=True,
                                 verbose_name='Контракт')

    def __str__(self):
        return f"{self.lead} | {self.contract}"

crm/service/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Service(models.Model):
    """Модель услуги"""

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    name = models.CharField(unique=True, max_length=255, verbose_name="Название услуги")
    description = models.TextField(
        blank=True, null=True, max_length=1023, verbose_name="Описание услуги"
    )
    price = models.DecimalField(
        default=0, max_digits=8, decimal_places=2, verbose_name="Цена услуги"
    )

    def __str__(self):
        """Возвращает название услуги"""
        return self.name

    def clean(self):
        """Валидация данных"""
        if len(self.name) > 255:
            raise ValidationError('Длина названия не может превышать 255 символов')

        if len(self.description) > 1023:
            raise ValidationError('Длина описания не может превышать 1023 символов')

        if self.price < 0 or self.price > 99999999.99:
            raise ValidationError('Цена должна быть в диапазоне 0.00 - 99,999,999.00')

    def save(self, *args, **kwargs):
        """Метод для сохранения данных при успешной валидации"""
        self.full_clean()
        return super().save(*args, **kwargs)

crm/users/models.py
from django.core.exceptions import ValidationError
from django.db import models

from adv_company.models import AdvCompany


class Lead(models.Model):
    """Класс лида"""

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    first_name = models.CharField(max_length=63, verbose_name="Имя")
    last_name = models.CharField(max_length=63, verbose_name="Фамилия")
    phone = models.CharField(unique=True, max_length=11, verbose_name="Номер телефона")
    email = models.EmailField(unique=True, verbose_name="Почта")
    ads = models.ForeignKey(
        AdvCompany, on_delete=models.PROTECT, verbose_name="Рекламная кампания"
    )
    is_active = models.BooleanField(default=False, verbose_name="Активный пользователь")

    def __str__(self):
        """Возвращает фамилию и имя лида"""
        return f"{self.last_name} {self.first_name}"

    def clean(self):
        if len(self.first_name) > 63:
            raise ValidationError('Длина имени не может превышать 63 символов')

        if len(self.last_name) > 63:
            raise ValidationError('Длина фамилии не может превышать 63 символов')

        if len(self.phone) != 11:
            raise ValidationError('Номер телефона должен состоять из 11 цифр')
        else:
            for element in self.phone:
                if element not in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
                    raise ValidationError('Номер телефона должен состоять только из цифр')

        if '@' not in self.email:
            raise ValidationError('В адресе почты обязательно должен присутствовать знак "@"')

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

crm/adv_company/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import PermissionRequiredMixin


from adv_company.models import AdvCompany
from customers.models import Customer
from users.models import Lead


class AdvListView(ListView, PermissionRequiredMixin):
    """Класс для просмотра списка всех рекламных кампаний"""

    permission_required: str = "advcompany.view_advcompany"
    model = AdvCompany
    queryset = AdvCompany.objects.prefetch_related("service").all()
    template_name: str = "adv/ads-list.html"
    context_object_name: str = "ads"


class AdvCreateView(CreateView, PermissionRequiredMixin):
    """Класс для создания новой рекламной кампании"""

    permission_required: str = "advcompany.add_advcompany"
    model = AdvCompany
    fields: list[str] = ["name", "service", "promotion_channel", "budget"]
    template_name: str = "adv/ads-create.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("advcompany:adv-list")


class AdvDetailView(DetailView, PermissionRequiredMixin):
    """Класс для просмотра подробной информации рекламной кампании"""

    permission_required: str = "advcompany.view_advcompany"
    model = AdvCompany
    template_name: str = "adv/ads-detail.html"


class AdvUpdateView(UpdateView, PermissionRequiredMixin):
    """Класс для обновления информации о рекламной кампании"""

    permission_required: str = "advcompany.change_advcompany"
    model = AdvCompany
    fields: list[str] = ["name", "service", "promotion_channel", "budget"]
    template_name: str = "adv/ads-edit.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("advcompany:adv-edit", kwargs={"pk": self.kwargs.get("pk")})


class AdvDeleteView(DeleteView, PermissionRequiredMixin):
    """Класс для удаления рекламной кампании"""

    permission_required: str = "advcompany.delete_advcompany"
    model = AdvCompany
    template_name: str = "adv/ads-delete.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy("advcompany:adv-list")


class AdvStatistics(View):
    """Класс для отображения статистики рекламных кампаний"""

    @staticmethod
    def get(request: HttpRequest) -> HttpResponse:
        """Метод get выводит статистику рекламных кампаний"""
        count = 0

        ads = AdvCompany.objects.prefetch_related("service").all()
        all_leads = Lead.objects.select_related("ads").all()
        all_customers = Customer.objects.select_related("lead", "contract").all()

        for ad in ads:
            leads = all_leads.filter(ads=ad)
            count += 1
            customers, price = 0, 0

            for lead in leads:
                try:
                    ss = all_customers.get(lead=lead)
                    price += ss.contract.service.price
                    customers += 1
                except ObjectDoesNotExist:
                    pass
            leads = all_leads.filter(ads=ad).count()
            ad.leads = leads
            ad.customers = customers
            ad.profit = price - ad.budget
        context = {"ads": ads}
        return render(request, "adv/ads-statistic.html", context=context)

crm/adv_company/templates/adv/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>
{% for message in messages %}
    <div class="alert {{ message.tags }}" role="alert">
        {{ message }}
    </div>
{% endfor %}
<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.service.view_service %}
            <li><a href="/products/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.adv_company.view_advcompany %}
            <li><a href="/ads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.users.view_lead %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contract %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customer %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            {% if user.is_authenticated %}
                <li><a href="/accounts/logout" class="bar-item text-decoration-none px-3 py-3 d-block">
                    <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
                </a></li>
            {% else %}
                <li><a href="/accounts/login" class="bar-item text-decoration-none px-3 py-3 d-block">
                    <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Вход</span>
                </a></li>
            {% endif %}
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

crm/adv_company/templates/adv/ads-create.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/ads/new/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/adv_company/templates/adv/ads-delete.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.name }}"?</p>
        <form method="POST" action="/ads/{{ object.pk }}/delete/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/adv_company/templates/adv/ads-detail.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.name }}</h5>
                <ul>
                    {% for service in object.service.all %}
                        <li><p class="card-text">{{ service.name }}</p></li>
                    {% endfor %}
                </ul>
                <div class="d-flex justify-content-end fw-bold">{{ object.budget }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="/ads/{{ object.pk }}/edit" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/adv_company/templates/adv/ads-edit.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/ads/{{ object.pk }}/edit/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/adv_company/templates/adv/ads-list.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Рекламные компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="/ads/new" class="btn btn-success p-2">Создать</a>
        <a href="/ads/statistic" class="btn btn-primary p-2">Статистика</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/ads/{{ ad.pk }}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <a href="/ads/{{ ad.pk }}/delete" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

crm/adv_company/templates/adv/ads-statistic.html
{% extends "adv/_base.html" %}

{% block content %}
<h2 class="fw-bold">Статистика рекламных компаний</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/ads/{{ ad.pk }}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <p>Лидов: {{ ad.leads }} | Активных клиентов: {{ ad.customers }} | Соотношение контрактов к затратам: {{ ad.profit|default_if_none:"-" }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}